### PR TITLE
Fix issue #129

### PR DESCRIPTION
**Pull request by genggjh**
1. Add [StatusCode](https://github.com/openblockchain/obc-peer/blob/master/protos/server_admin.proto#L36)
in the "status", "stop" and "vm" commands stdout result.

2. Change the file format from dos to unix.

Signed-off-by: David Geng <david@esse.io>

### CODE REVIEW

**Comment by genggjh** [comment]
Signed-off-by: David Geng<david@esse.io>

**Comment by genggjh** [comment]
Anyone can give me some comments for this change?

**Comment by binhn** [comment]
@genggjh I can't tell where the changes are. Why every line deleted and added? Could you resubmit the commit with only the changes.

**Comment by genggjh** [comment]
@binhn , my changes are here:
-`status` | String form of ServerStatus_StatusCode
-`stop`   | String form of ServerStatus_StatusCode
-`login`  | N/A
-`vm`     | String form of ServerStatus_StatusCode
+`status` | String form of [StatusCode](https://github.com/openblockchain/obc-peer/blob/master/protos/server_admin.proto#L36)
+`stop`   | String form of [StatusCode](https://github.com/openblockchain/obc-peer/blob/master/protos/server_admin.proto#L36)
+`login`  | N/A
+`vm`     | String form of [StatusCode](https://github.com/openblockchain/obc-peer/blob/master/protos/server_admin.proto#L36)


Other things, I think should be I changed the file type from doc to unix related. I think we should keep the file type always in unix like others, right?

**Comment by joshhus** [comment]
I've been seeing the same problem recently in the GitHub editor - it displays every section of an edited file as changed, even for only one single line change. Do we have GitHub support we can inquire with? it wasn't previously doing this - I will investigate GitHub support.

**Comment by genggjh** [comment]
@joshhus, by my understanding, this should be the file type has been changed related. But anyway, confirm with GitHub support is not bad.

**Comment by joshhus** [comment]
I see. I have changed nothing in my usage of the editor that would explain this change, however. So perhaps the editor changed. I will post when GH responds.

**Comment by genggjh** [comment]
@joshhus , please help to review my new patch, I am glad to see your comments.

**Comment by joshhus** [comment]
@genggjh ... Please clarify, what is the "new patch" exactly. Thanks. ... I have not heard back from GitHub on the file type question yet. What is our request - that they support any and all file types? With team members using various editors and Macs, PCs, and UNIX, only supporting one file type could be burdensome. ?? What is our preference / request for this support? Thanks. @binhn

**Comment by genggjh** [comment]
@joshhus , new patch is here, just rebased the comments from master batch.
https://github.com/genggjh/obc-docs/commit/68c95a3ba2874f5a37c420106505f026a263142e

**Comment by joshhus** [comment]
This is a syntax change: so "ServerStatus_StatusCode" is now just "ServerStatus" on 3 lines - view the patch for specifics. Need dev. to confirm / approve. The other additions are links to the doc for "StatusCode". @angrbrd

**Pull request merged**
