### PR TITLE
Added OBC-CA Documentation.

### PR DESCRIPTION
**Pull request by thkzrl**
TLS setup documentation should be added by Diego Angel Masini.

Signed-off-by: Thorsten Kramp <thk@zurich.ibm.com>

### CODE REVIEW

**Comment by thkzrl** [comment]
Will do.

**Comment by joshhus** [comment]
ID reviewed: 
For obcca-api.md, please update:
1. "namly" typo (namely)
2. change "allows to register" to "allows you to register" or similar.
3. (what is a "struct" - spell out as "structure" ?)
4. add a colon char: "... provides the following functions:"
5. "The `ReadCACertificate` functions returns" - use either function or returns not both.
6. "The `CreateCertificatePair` functions allows" - use either functions or allows not both.
7. "auditors only to retrieve" ... clarify does this mean "only auditors" can do it, or rather that auditors can "only retrieve" ... delete "only" perhaps.
8. 2nd instance of #5 - "The `ReadCACertificate` functions returns" - use either function or returns not both.
9. The `ReadCertificate` allows -- add "function"

**Comment by joshhus** [comment]
ID also reviewed:
For obcca-setup.md, please update:
1. change "for data signing, one for data" to "for data signing, and one is for data"
2. change "then can request" to "can then request"
3. change "then is converted" to "is then converted"
4. delete "so-called" 
5. change "can be requested form" to "can be requested from"
6. change "in the CA's configuration file called _obcca.yaml_ located in the same directory next to the CA binary" to "in the CA configuration file obcca.yaml, which is located in root of the same directory as the CA binary"
7. change "number operating-system threads" to "number of operating system threads"
8. change "users like this" to "users, where each user's name, roles, and password are specified:" and then delete the subsequent "whereby" phrase.
9. change "simply is" to "is simply" 
10. change "generate all its required state" to "generate all of its required states" (assuming state is plural here?)
11. change "..." to "etc." 
12. change "and writes this state" to "and write each state" (note: if "states" is singular, then rephrase 10 and 12 as appropriate.)
13. delete "for now" or rephrase as the "current default" or similar.
14. change "certificates by root-signed one." to "certificates with root-signed ones."
15 change "same location as where the server binary is located." to "same location as the server binary."

**Comment by thkzrl** [comment]
Thanks.  Corrected in new PR.

**Pull request closed without merging**
