### PR TITLE
changed TCertOwner_EncryptKey to subscript where required

### PR DESCRIPTION
**Pull request by clydedacruz**
Made small corrections to protocol-spec.md, to make cryptography related syntax consistent with the rest of the document.

Changed AES_Encrypt TCertOwner_EncryptKey   to AES_Encrypt<sub>TCertOwner_EncryptKey<sub>

### CODE REVIEW

**Comment by clydedacruz** [comment]
Signed-off-by:Clyde DCruz clydcruz@in.ibm.com

**Comment by clydedacruz** [comment]
@angrbrd or  Please could you review this ? Thanks.

**Comment by angrbrd** [comment]
Hi @clydedacruz , thank you submitting this PR. You submitted this right as we were in the process of moving our code/docs to the hyperledger project and must have missed your PR in the process.

We have two options:

(1) You open a new PR to the hyperledger codebase and I will merge it for you, as all new PRs need to go to hyperledger. https://github.com/hyperledger/fabric/tree/master/docs
(2) I close and submit your change into hyperledger myself. 

I am fine with either (1) or (2). Please reply which you would prefer. Thanks!

**Comment by clydedacruz** [comment]
(1) Ok I will submit a PR to the Hyperledger repository . Thanks!

**Comment by clydedacruz** [comment]
Here is the relevant PR in the Hyperledger repo  https://github.com/hyperledger/fabric/pull/970

**Comment by angrbrd** [comment]
Hi @clydedacruz, your PR to Hyperledger has been merged.

https://github.com/hyperledger/fabric/pull/970

I am closing this PR as well as issue #167. 

Thanks!

**Pull request closed without merging**
